version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root   
    networks:
      - web_api
    volumes:
      - db:/var/lib/mongodb/data
  side:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    restart: always
    ports:
      - 8080:8080
    networks:
      - web_api
    command: ["./side", "serve"]

volumes:
  db:

networks:
  web_api:
    driver: bridge